// <auto-generated />
namespace Phonebook.InfraStructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class db_phonebook_v3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db_phonebook_v3));
        
        string IMigrationMetadata.Id
        {
            get { return "201803211740008_db_phonebook_v3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
